version: '3'

services:

  app:
    build:
      context: nodejs
    container_name: app
    networks:
      - node-network
    volumes: 
      - ./nodejs:/usr/src/app
    tty: true
    ports: 
      - 3001:3000
    # esse comando indica que um container é dependente do outro
    # depends_on: 
      #- db

  db:
    image: mysql:5.7.16
    command: --innodb-use-native-aio=0
    container_name: db
    # se por algum motivo o container cair, vai reiniciar sozinho
    # restart: always
    # se precisar entrar no container, o tty deve estar habilitado
    # /media/adrianowy/DATA/projetos_web/fullcycle/docker/mysql
    tty: true
    volumes:
      - ./mysql3:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - node-network

networks: 
  node-network:
    driver: bridge