version: '3'

services:

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    # se por algum motivo o container cair, vai reiniciar sozinho
    restart: always
    # se precisar entrar no container, o tty deve estar habilitado
    tty: true
    volumes:
      - ./mysql:var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - node-network

networks: 
  node-network:
    driver: bridge